import concat from './concat.mjs'
import copyWithin from './copyWithin.mjs';
import entries from './entries.mjs';
import every from './every.mjs';
import arrayFill from './fill.mjs';
import filter from './filter.mjs';
import find from './find.mjs';
import findIndex from './findindex.mjs';
import flat from './flat.mjs';
import flatMap from './flatmap.mjs';
import forEach from './foreach.mjs';
import from from './from.mjs';
import includes from './includes.mjs';
import indexOf from './indexof.mjs';
import isArray from './isarray.mjs';
import Iterate from './iterator.mjs'
import join from './join.mjs';
concat();
Iterate();
copyWithin();
entries();
every();
arrayFill();
filter();
find();
findIndex();
flat();
flatMap();
forEach();
from();
includes();
indexOf();
isArray();
join();